[package]
name = "phonebook"
version = "0.1.0"
edition = "2021"

[dependencies]
socrates = { path = "../socrates" }
tokio = { version= "1.43.0", features = ["full"] }
serde = { version = "1.0.217" , features = ["derive", "rc"] }
axum = "0.8.1"